### ISSUE TITLE
Make the widget background transparent and include more information 

### ISSUE THREAD

**Issue by vivadavid** [darkmoonight/Rain#107]
Hi,

First of all, thank you for adding a widget to the app. I've quickly tried it, but I was wondering if there could be an option to make the background transparent.

Also, resizing the widget doesn't make it display more information.

Thanks!

**Comment by Leonavichus** [comment]
Hi, as I already wrote in #1, all this is already in the plans. I am still developing in creating widgets and will add new features as I study.

**Comment by vivadavid** [comment]
> Hi, as I already wrote in #1, all this is already in the plans. I am still developing in creating widgets and will add new features as I study.

Thanks!

**Comment by shatanikmahanty** [comment]
@Leonavichus I did some research into widget transparency and achieved it using this code:

![image](https://github.com/DarkMooNight/Rain/assets/67138059/134656c0-99e8-408a-baae-23e44d72516b)

Would it be a good idea to let users pick the color for the widget using a color picker inside the app settings? And then call the update widget method in the controller?

I can work on a PR on this if you want! In this manner we would be giving lots of customizability rather than directly setting it transparent.

**Comment by Leonavichus** [comment]
@shatanikmahanty, You are my salvation, you would help me a lot with this! I would be very grateful for your help! 🙏

**Comment by shatanikmahanty** [comment]
> @shatanikmahanty, You are my salvation, you would help me a lot with this! I would be very grateful for your help! 🙏

Would get back with a pr soon ☺️
